### ISSUE TITLE
What is this item?

### ISSUE THREAD

**Issue by marcosscriven** [blazra/spinmatrix#1]
Hi there

I'm just looking for STL and OpenSCAD files to add to my site, and found this.

However, just wondering what it's for please? There's nothing in the README file.

Sorry if it's a dumb question!

Thanks

Marcos

**Comment by blazra** [comment]
Hi, it will be rotating LED display. Project is now paused...

**Comment by marcosscriven** [comment]
Ah... Cool!

Shame it's paused :)

Just to let you know the site I was talking about is http://www.fabfabbers.com/models/

Thanks

Marcos

**Comment by blazra** [comment]
Sync with github and openscad in browser - nice!
